#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Mar 10 13:24:32 CET 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 1f06effad98c45e2b525b6ab8c42b99a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_clock_enable_behav xil_defaultlib.tb_clock_enable -log elaborate.log"
xelab -wto 1f06effad98c45e2b525b6ab8c42b99a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_clock_enable_behav xil_defaultlib.tb_clock_enable -log elaborate.log

